### ISSUE TITLE
Message separators (date and unread) displaying as black bars

### ISSUE THREAD

**Issue by Eir-nya** [DiscordStyles/SoftX#129]
**Describe the bug**  
Message date and unread message separators seem to have suddenly changed appearance. The latter displays as a thin black bar, missing the "new" label.

**Screenshots**  
Date separator
![1](https://github.com/DiscordStyles/SoftX/assets/18407857/e5eb577a-8f28-42cf-8acf-32b91f21ae41)
Date separator (unread) (only the text turns red? I seem to remember the whole line turned red and it said "new", which it doesnt here)
![2](https://github.com/DiscordStyles/SoftX/assets/18407857/902abd96-c374-42ad-8191-58a0985efda5)
Unread message separator (on the last message. missing the "new" label on the right side)
![4](https://github.com/DiscordStyles/SoftX/assets/18407857/0c32512c-b218-4f1c-8f87-b7ddf387f5b2)

These screenshots are using unmodified SoftX.

**Infomation (please complete the following information):**  
Discord channel: Stable 307392
OS: Linux
Mod: Vencord
Discord language: English

**Comment by Strana** [comment]
I've noticed this issue when it started occurring as well, this definitely shouldn't be happening, and it just makes things look weird.

**Comment by Tremji08** [comment]
Same here

**Comment by FireBoy00** [comment]
I made a fix for the red bar. 
```css
.divider_d5deea#---new-messages-bar::before {
    background: var(--divider-color) !important;
}
```

Also, if you want that the normal date separator bar to not be black and be same color as the text here is a thing for that as well:
```css
.divider_d5deea::before {
    background: var(--text-muted) !important;
}
```

As for the `new` label... well that I don't know how to fix 😅. Hope this helps.
**P.S.:** _To implement the fix simply add the lines of code into the `Custom CSS Editor`_
