### ISSUE TITLE
Enhancement: Bigger Borders for Dragging the Window

### ISSUE THREAD

**Issue by hofq** [DiscordStyles/SoftX#27]
Hi,
it would be cool if you could use the whole Bar (only empty space of cause) to Drag the Window to make it more practical:

![grafik](https://user-images.githubusercontent.com/54744977/157320741-6b1a2dc2-c4a9-4156-9e28-0c72118f457d.png)

**Comment by Gibbu** [comment]
Added, might remove if too many complaints.

**Comment by hofq** [comment]
This is Great! Sadly i the hitbox of the Window-Interaction Buttons is a bit wired/off, is that related?
![grafik](https://user-images.githubusercontent.com/54744977/160849097-071efdd1-62d2-4058-8b3e-e02d1bdb4588.png)

**Comment by Gibbu** [comment]
Dang, I don't think there's a way to do this then. I've added a `--TB-bar-height` variable to increase the height of the invisible bar at the top.
Add it inside your `SoftX.theme.css` `:root` brackets.

Example:
```css
@import url("https://discordstyles.github.io/SoftX/SoftX.css");

:root {
  --background-image: url("...");
  /* other variables... */

  --TB-bar-height: 12px;
}
```
