### ISSUE TITLE
discord top bar to thick

### ISSUE THREAD

**Issue by AestheticGod19** [DiscordStyles/SoftX#42]
how i can make the top bar smaller
https://imgur.com/a/VcooN6y

**Comment by Gibbu** [comment]
You can decrease the height of the toolbar with
```css
:root {
  --toolbar-height: 74px;
}
```
Paste that into your CustomCSS tab.
