### ISSUE TITLE
User profile shifted greatly to the left

### ISSUE THREAD

**Issue by KayaGG** [DiscordStyles/SoftX#43]
User profile is shifted to the left 

Latest update, i would assume

![image](https://user-images.githubusercontent.com/76425329/168642813-93b1918b-1a79-49b9-8fd1-bb705252dae5.png)

**Infomation (please complete the following information):**  
Discord channel: Stable
OS: win 10  
Mod: BetterDiscord  
Discord language: English

**Comment by Gibbu** [comment]
Discord pushing it *very* slowly. I'll fix it once I get it.

**Comment by KayaGG** [comment]
Any updates on this?

**Comment by Yukai-Qian** [comment]
I was able to fix this by adding the following lines to BetterDiscord's custom CSS:

```css
#app-mount .nameTag-sc-gpq.canCopy-IgTwyV {
    display: none !important;
}

#app-mount .withTagAsButton-OsgQ9L, .withTagless-10ooWt {
    min-width: 44px;
}
```

Hope it works for you, too.
