### ISSUE TITLE
Suggestion: move Vertical User Area's tooltips to the right of the buttons

### ISSUE THREAD

**Issue by Yukai-Qian** [DiscordStyles/SoftX#53]
For Vertical User Area, if the server list width is not very large, the tooltips (especially that of the User Settings) might get clipped by the window border. It might be desirable to move the tooltips to the right of the buttons. Below is one possible implementation:

```css
#app-mount .tooltip-14MtrL :not(.tooltipRight-2TSb42) {
    left: calc(50% + 45px);
    top: 46px;
}

#app-mount .tooltipPointer-3L49xb {
    display: none;
}
```

Effect:

![image](https://user-images.githubusercontent.com/100383998/176424061-79a7d6bc-2a2d-488b-a75e-758ad14b7f69.png)
