### ISSUE TITLE
Theme doesn't allow use of Window's Snapping Features

### ISSUE THREAD

**Issue by ErikDombi** [DiscordStyles/SoftX#69]
The way the theme treats the taskbar currently, snapping to fullscreen by dragging the app to the top of your screen no longer works. Dragging out of full screen also does not return the window to a windowed state. Is there any way to fix this, or is this some weird electron trickery needed to make the theme work?

**Comment by Gibbu** [comment]
There's a 9px high box close to the top of the screen that still keeps the functionality.
If you want to see it, add this to your CustomCSS tab.
```css
.platform-win .typeWindows-2-g3UY {
  background: hsl(0 0% 100% / .15);
}
```
