### ISSUE TITLE
glow-intensity and background-blur broken

### ISSUE THREAD

**Issue by jasonborn0** [DiscordStyles/SoftX#81]
**Describe the bug**  
*((A clear and concise description of what the bug is))*  
The parameter glow-intensity and background-blur seems to be broken, as changing it (as well as related parameters such as channel-glow-intensity) does not do anything. 

The current unread glow is a bit too bright for me, so I was trying to find a way to dim the glow a bit. 

**To Reproduce**  
*((Steps to reproduce the behavior))*  
Changing glow-intensity or background-blur in .css

**Screenshots**  
*((If applicable, add screenshots to help explain your problem))*  

**Infomation (please complete the following information):**  
Discord channel: *((Stable/PTB/Canary))*  Stable
OS: *((Windows/Linux/OSX))*  Windows
Mod: *((BetterDiscord/Powercord))*  BetterDiscord
Discord language: *((Your language))*  English

**Additional context**  
*((Add any other context about the problem here. Remove if not applicable.))*

**Comment by Gibbu** [comment]
All variables you mention work as intended.
Can you provide the CSS you're using?

**Comment by jasonborn0** [comment]
> All variables you mention work as intended. Can you provide the CSS you're using?

Here it is: 

```css
/**
 * @name SoftX
 * @author Gibbu
 * @version 1.0.0
 * @description A soft and comfy feel for Discord.
 * @source https://github.com/DiscordStyles/SoftX
 * @invite ZHthyCw
*/

@import url("https://discordstyles.github.io/SoftX/SoftX.css");

/* Google Fonts */
@import url("https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500&display=swap");
/* Theme imports */
@import url("https://discord-custom-covers.github.io/usrbg/dist/usrbg.css");
@import url("https://discordstyles.github.io/SoftX/RadialGlow.css"); /* RadialGlow effect for avatars. | Remove this line to disable. */
/* @import url("https://discordstyles.github.io/Addons/windows-titlebar.css"); Windows titlebar. | Remove this line to disable. */
:root {
  /*
   * SoftX variables
   */
  --channel-glow-intensity: 0.5;
  --toolbar-height: 56px; /* default: 74px */
  /* disables chat bubble */
  /* --chat-bubble-bg: transparent;
  --chat-bubble-bg-self: transparent;
  --chat-bubble-padding: 0;
  --chat-bubble-display: block; */
  /* Background image | URL MUST BE A DIRECT LINK (ending in .jpg, .jpeg, .png, .gif) */
  --background-image: url("https://i.imgur.com/Nglfni6.png");
  --background-blur: 80px; /* Blur intensity of --background-image | Must end in px | Default: 0px */
  --accent: 147, 149, 247; /* Colour used around the app. | Values are in R,G,B format. | Default: 0, 231, 169 */
  --channels-width: 250px; /* Width of the channels list. | Default: 300px */
  --guilds-width: 85px; /* Width of the server list. | Default: 105px */
  --members-width: 280px; /* Width of the members list. | Default: 280px */
  --server-size: 50px; /* Size of the servers inside the server list. | Default: 50px */
  --chat-avatar-size: 46px; /* Size of the chat avatars. | Default: 32px */
  --glow-intensity: 1; /* Intensity of the glow used around the app. | Set to 0 to disable the glow. | Decimals allowed | Default: 1 */
  --opacity: 0.8; /* Opacity of overall app. | Default: .85 */
  --font: "Inter"; /* Custom font | Default: 'Inter' */
  --avatar-roundness: 50%; /* Roundness for avatars. | 0% = Square, 50% = Circle | Default: 50% */
  --server-roundness: 50%; /* Roundness for servers. | 0% = Square, 50% = Circle | Default: 50% */
  /*
   * RadialStatus veriables
   */
  --rs-small-spacing: 2px; /* Spacing between profile image and outer ring on small icons (e.g. member list) | Default: 2px */
  --rs-medium-spacing: 4px; /* Spacing between profile image and outer ring on medium icons (e.g. user popout) | Default: 4px */
  --rs-large-spacing: 4px; /* Spacing between profile image and outer ring on medium icons (e.g. user popout fullscreen) | Default: 4px */
  --rs-small-width: 1.5px; /* Ring width (follows same sizing as above) | Default: 1.5px */
  --rs-medium-width: 2px; /* Default: 2px */
  --rs-large-width: 2px; /* Default: 2px */
  /* Customizable colors */
  --rs-online-color: #9395f7; /* Default: #43b581 */
  --rs-idle-color: #faa61a; /* Default: #faa61a */
  --rs-dnd-color: #f04747; /* Default: #f04747 */
  --rs-offline-color: #636b75; /* Default: #636b75 */
  --rs-streaming-color: #643da7; /* Default: #643da7 */
  --rs-invisible-color: #747f8d; /* Default: #747f8d */
  --rs-phone-color: var(
    --rs-online-color
  ); /* Color of the phone for mobile users | Default: var(--rs-online-color) */
  --rs-phone-visible: block; /* Visibility of the phone for mobile users | Default: block */
}
```

**Comment by Gibbu** [comment]
Yep... It works?

`0.5`
![Discord_8chhPiyehH](https://user-images.githubusercontent.com/20338746/224686495-a6b75050-266a-420f-bacc-4427e8a35d9b.png)

`1`
![Discord_Rf7epTzel9](https://user-images.githubusercontent.com/20338746/224686577-7818b8df-0460-45c4-a008-fd4a96956725.png)

**Comment by jasonborn0** [comment]
@Gibbu 
Just tried changing again and it works. That's really weird. 

Do you get blurred background when changing --background-blur? For me it does nothing:

8px
<img width="228" alt="Screenshot 2023-03-13 104224" src="https://user-images.githubusercontent.com/122321879/224784775-990754fc-0d76-41e0-995d-1266387f3e91.png">
0px
<img width="225" alt="Screenshot 2023-03-13 104233" src="https://user-images.githubusercontent.com/122321879/224784779-fd25709b-9ffc-44c9-9604-fb78d83946b0.png">

**Comment by Gibbu** [comment]
Sorry for the late reply. I'm not sure why your background is not being blurred as mine works just fine.

0px
![Discord_5oZ3Bb0e7d](https://user-images.githubusercontent.com/20338746/226102007-3c994681-97c0-4447-90f9-4c9b70c71bd1.png)

8px
![Discord_cpWawhiG36](https://user-images.githubusercontent.com/20338746/226102012-61298da7-4ad2-417c-9295-6012cbbf5eb4.png)


And these are all the available variables for the server rings.

```css
:root {
  --server-unread-colour: 255, 255, 255;
  --server-hover-colour: 255, 255, 255;
  --server-selected-colour: var(--accent, 0, 231, 169);
  --server-glow-intensity: 1;
}
```
